// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8zFy7tU06gfuqJNUSlIrGra6gVbH2CjE',
    appId: '1:560664313137:web:6b8b1acc2db5db903d8410',
    messagingSenderId: '560664313137',
    projectId: 'kitpay-a804d',
    authDomain: 'kitpay-a804d.firebaseapp.com',
    storageBucket: 'kitpay-a804d.appspot.com',
    measurementId: 'G-7GQGRS2L0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-oLe4wB_k_ihS--EQCIOOwBuXdx5pjwI',
    appId: '1:560664313137:android:0b94969d2a6ac25b3d8410',
    messagingSenderId: '560664313137',
    projectId: 'kitpay-a804d',
    storageBucket: 'kitpay-a804d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC8wx4aKK6aomlLtdVCQPm7Ec021Tpebk',
    appId: '1:560664313137:ios:feba8826a3ba9d133d8410',
    messagingSenderId: '560664313137',
    projectId: 'kitpay-a804d',
    storageBucket: 'kitpay-a804d.appspot.com',
    iosBundleId: 'com.kitpay.ejapay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC8wx4aKK6aomlLtdVCQPm7Ec021Tpebk',
    appId: '1:560664313137:ios:feba8826a3ba9d133d8410',
    messagingSenderId: '560664313137',
    projectId: 'kitpay-a804d',
    storageBucket: 'kitpay-a804d.appspot.com',
    iosBundleId: 'com.kitpay.ejapay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8zFy7tU06gfuqJNUSlIrGra6gVbH2CjE',
    appId: '1:560664313137:web:ddac327fdba51ec43d8410',
    messagingSenderId: '560664313137',
    projectId: 'kitpay-a804d',
    authDomain: 'kitpay-a804d.firebaseapp.com',
    storageBucket: 'kitpay-a804d.appspot.com',
    measurementId: 'G-BFZQB4WQ05',
  );
}
